[package]
name = "rust-week-bot"
version = "0.1.0"
authors = ["Francesco Uliana <francesco@uliana.it>"]

[dependencies]
egg-mode = "0.11.0"
slack-hook = "0.6"
tokio-core = "0.1.10"
dotenv = "0.10.1"
redis = "0.8.0"
regex = "0.2"

futures = "0.1"
hyper = "0.11"

reqwest = "0.8.1"
select = "0.4.2"